services:
  # TODO: add wings and pterodactyl
  ptero-billing_development:
    build:
      context: ../../
      dockerfile: ./docker/standalone/Dockerfile
    container_name: ptero-billing_development
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../..:/var/www/html:rw"
      - "./nginx_config:/etc/nginx/conf.d/:rw"
    networks:
      - ptero-billing

  mysql:
    image: mysql
    container_name: ptero-billing_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ptero-billing
      MYSQL_USER: ptero-billinguser
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./mysql:/var/lib/mysql:delegated"
    networks:
      - ptero-billing

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ptero-billing_phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=ptero-billing_mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_ARBITRARY=1
    networks:
      - ptero-billing

  redis:
    image: redis
    container_name: ptero-billing_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ptero-billing

networks:
  ptero-billing:
